image: Visual Studio 2017

version: 0.0.1.{build}

environment:
  NUGET_API_KEY:
    secure: Xgfg93dEsB7PeszT3oyiQNkB8gLvYTzREf859tknmjkVm9IvsVu75kMpVLm6fYfr

build:
  verbosity: minimal

init:
- ps: |
    $env:build=$env:APPVEYOR_BUILD_NUMBER
    $lastDot = $env:APPVEYOR_BUILD_VERSION.LastIndexOf(".")
    $env:version=$env:APPVEYOR_BUILD_VERSION.Substring(0, $lastDot)

    # This was a tag triggered build
    if ($env:appveyor_repo_tag -eq "true") {
        $env:tag=$env:appveyor_repo_tag_name
    }

build_script:
- ps: >-
    ./build.ps1 -t build

test_script:
- ps: ./build.ps1 -t test

deploy_script:
- ps: |
    if ($env:appveyor_repo_tag -eq "true") {
        ./build.ps1 -t push
    }
